# Generated by Django 4.0.1 on 2022-01-19 16:52

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='简介')),
                ('date', models.DateTimeField(default='', verbose_name='时间')),
                ('image', models.CharField(blank=True, default='', max_length=255, verbose_name='封面')),
                ('tags', models.CharField(blank=True, default='', max_length=255, verbose_name='标签')),
                ('categories', models.CharField(blank=True, default='', max_length=255, verbose_name='分类')),
                ('series', models.CharField(blank=True, default='"Themes Guide"', max_length=255, verbose_name='待定01')),
                ('aliases', models.CharField(blank=True, default='"migrate-from-jekyl"', max_length=255, verbose_name='待定02')),
                ('other', models.CharField(blank=True, default='', max_length=255, verbose_name='其他')),
                ('content', mdeditor.fields.MDTextField(blank=True, default='', verbose_name='正文')),
            ],
            options={
                'verbose_name': '关于',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='简介')),
                ('date', models.DateTimeField(default='', verbose_name='时间')),
                ('image', models.CharField(blank=True, default='', max_length=255, verbose_name='封面')),
                ('tags', models.CharField(blank=True, default='', max_length=255, verbose_name='标签')),
                ('categories', models.CharField(blank=True, default='', max_length=255, verbose_name='分类')),
                ('series', models.CharField(blank=True, default='"Themes Guide"', max_length=255, verbose_name='待定01')),
                ('aliases', models.CharField(blank=True, default='"migrate-from-jekyl"', max_length=255, verbose_name='待定02')),
                ('other', models.CharField(blank=True, default='', max_length=255, verbose_name='其他')),
                ('content', mdeditor.fields.MDTextField(blank=True, default='', verbose_name='正文')),
            ],
            options={
                'verbose_name': '博客列表',
            },
        ),
    ]
